ungrouped:  # This specifies that the following properties apply to all hosts in the inventory.

  hosts:
    managedhost-app-1:  # First managed host
      ansible_host: 0.0.0.0  # IP address of the managed host
      ansible_connection: ssh  # Using SSH for connection
      ansible_port: 2223  # Consistent with the SSH port configured in docker-compose.yml for managedhost-app-1
      ansible_user: root  # User to connect with (root in this case)

    managedhost-app-2:  # Second managed host
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2224  # Consistent with the SSH port configured in docker-compose.yml for managedhost-app-2
      ansible_user: root

    managedhost-app-3:  # Third managed host
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2225  # Consistent with the SSH port configured in docker-compose.yml for managedhost-app-3
      ansible_user: root


app_group:  # Host group for all managed hosts
  hosts:
    managedhost-app-1:
    managedhost-app-2:
    managedhost-app-3: